name = "cloud-media-host"
main = "src/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Variables de entorno
[vars]
ENVIRONMENT = "production"
MAX_FILE_SIZE = "104857600"
